
<?php
$_option = $block->getOption();
$class = ($_option->getIsRequire()) ? ' required' : '';

?>
<div class="select-wrapper<?php /* @escapeNotVerified */ echo $class; ?>">
   
        <?php echo $block->getValuesHtml() ?>
        <?php if ($_option->getIsRequire()): ?>
            <?php if ($_option->getType() == \Magento\Catalog\Model\Product\Option::OPTION_TYPE_RADIO || $_option->getType() == \Magento\Catalog\Model\Product\Option::OPTION_TYPE_CHECKBOX): ?>
                <span id="options-<?php /* @escapeNotVerified */ echo $_option->getId() ?>-container"></span>
            <?php endif; ?>
        <?php endif;?>
    
</div>
